apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop-scc-admin
rules:
- verbs:
    - '*'
  resources:
    - clusterrolebindings
  apiGroups:
    - rbac.authorization.k8s.io