kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-secrets-reader
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:  
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets